services:
  dvrk-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: dvrk_dev
    user: "1000:1000"
    volumes:
      # Mount the entire project directory
      - ..:/app
      # Mount the X11 socket for GUI forwarding
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      # Forward the display
      - DISPLAY=:1
      # Grant access to the X server
      - QT_X11_NO_MITSHM=1
      # NVIDIA Container Runtime
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      # Set matplotlib cache directory to avoid warnings
      - MPLCONFIGDIR=/tmp/matplotlib
    # Use the host's network stack for seamless X11 forwarding
    network_mode: "host"
    # Keep the container running
    stdin_open: true
    tty: true
    # GPU configuration - using runtime approach for better compatibility
    runtime: nvidia
